export const managementConfig = {
  karyawan: {
    title: "Karyawan",
    singular: "Karyawan",
    icon: "users",
    breadcrumb: ["Dashboard", "Management", "Karyawan"],
    namaLabel: "Nama Karyawan",
    tipeLabel: "Departemen",
    tipeOptions: ["Engineering", "Product", "Finance", "HR", "Sales", "Operasional"],
    statusOptions: ["Aktif", "Cuti", "Resign"],
    statusColors: { Aktif: "green", Cuti: "orange", Resign: "red" },
    showNilai: false,
    extraFields: [
      { key: "nomorInduk", label: "Nomor Induk (NIK/NIP)", type: "text" },
      { key: "jabatan", label: "Jabatan", type: "text" },
      { key: "tanggalMasuk", label: "Tanggal Masuk", type: "date" },
      { key: "tanggalKeluar", label: "Tanggal Keluar (kalau resign)", type: "date" },
      { key: "gajiPokok", label: "Gaji Pokok (Rp)", type: "number" },
      { key: "userId", label: "User ID Login (opsional)", type: "text" },
      { key: "cabangId", label: "Cabang", type: "cabang" },
    ],
  },
  aset: {
    title: "Aset",
    singular: "Aset",
    icon: "boxes",
    breadcrumb: ["Dashboard", "Management", "Aset"],
    namaLabel: "Nama Aset",
    tipeLabel: "Kategori Aset",
    tipeOptions: ["Elektronik", "Kendaraan", "Furniture", "Software", "Lainnya"],
    statusOptions: ["Baik", "Rusak Ringan", "Rusak Berat", "Maintenance"],
    statusColors: { Baik: "green", "Rusak Ringan": "orange", "Rusak Berat": "red", Maintenance: "blue" },
    showNilai: true,
    nilaiLabel: "Nilai Aset (Rp)",
    extraFields: [
      { key: "lokasi", label: "Lokasi", type: "text" },
      { key: "penanggungJawab", label: "Penanggung Jawab", type: "text" },
      { key: "tanggalPembelian", label: "Tanggal Pembelian", type: "date" },
      { key: "masaGaransi", label: "Masa Garansi Sampai", type: "date" },
      { key: "cabangId", label: "Cabang", type: "cabang" },
    ],
  },
  operasional: {
    title: "Operasional",
    singular: "Aktivitas",
    icon: "settings",
    breadcrumb: ["Dashboard", "Management", "Operasional"],
    namaLabel: "Nama Aktivitas",
    tipeLabel: "Jenis Aktivitas",
    tipeOptions: ["Maintenance", "Inspeksi", "Training", "Rapat", "Lainnya"],
    statusOptions: ["Pending", "Proses", "Selesai"],
    statusColors: { Pending: "orange", Proses: "blue", Selesai: "green" },
    showNilai: false,
    extraFields: [],
  },
  project: {
    title: "Project",
    singular: "Project",
    icon: "folder",
    breadcrumb: ["Dashboard", "Management", "Project"],
    namaLabel: "Nama Project",
    tipeLabel: "Kategori",
    tipeOptions: ["Internal", "Klien", "Riset"],
    statusOptions: ["On Track", "Warning", "Delay", "Selesai"],
    statusColors: { "On Track": "green", Warning: "orange", Delay: "red", Selesai: "blue" },
    showNilai: false,
    extraFields: [
      { key: "tanggalMulai", label: "Tanggal Mulai", type: "date" },
      { key: "tanggalSelesai", label: "Tanggal Selesai", type: "date" },
      { key: "anggota", label: "Anggota Tim (pisah koma)", type: "list" },
      { key: "budget", label: "Budget (Rp)", type: "number" },
    ],
  },
  finance: {
    title: "Finance",
    singular: "Transaksi",
    icon: "landmark",
    breadcrumb: ["Dashboard", "Management", "Finance"],
    namaLabel: "Deskripsi Transaksi",
    tipeLabel: "Tipe",
    tipeOptions: ["Pemasukan", "Pengeluaran"],
    statusOptions: ["Lunas", "Pending"],
    statusColors: { Lunas: "green", Pending: "orange" },
    showNilai: true,
    nilaiLabel: "Nominal (Rp)",
    extraFields: [
      { key: "kategoriId", label: "Kategori Finance", type: "finance-kategori" },
      { key: "metodePembayaran", label: "Metode Pembayaran", type: "select", options: ["Transfer", "Cash", "Kartu"] },
      { key: "nomorReferensi", label: "Nomor Invoice/Kwitansi", type: "text" },
      { key: "cabangId", label: "Cabang", type: "cabang" },
    ],
  },
  sales: {
    title: "Sales",
    singular: "Deal",
    icon: "cart",
    breadcrumb: ["Dashboard", "Management", "Sales"],
    namaLabel: "Nama Deal / Produk",
    tipeLabel: "Kategori",
    tipeOptions: ["Baru", "Renewal", "Upsell"],
    statusOptions: ["Lunas", "Pending", "Batal"],
    statusColors: { Lunas: "green", Pending: "orange", Batal: "red" },
    showNilai: true,
    nilaiLabel: "Nominal Penjualan (Rp)",
    extraFields: [
      { key: "customerId", label: "Customer ID (CRM, opsional)", type: "text" },
      { key: "produkId", label: "Produk ID (opsional)", type: "text" },
    ],
  },
};

export const managementCategories = Object.keys(managementConfig);
